### manager
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDBlYjZmMDM5ZjUyYTNhYzZiMTQwYiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc0NDkwMDc2MSwiZXhwIjoxNzQ0OTA0MzYxfQ.77glQAxsVmYAs7kdar5QwVYmEWOEIR1ToPtyD72xLVM
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDBlYjZmMDM5ZjUyYTNhYzZiMTQwYiIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20iLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc0NDkwMDc2MSwiZXhwIjoxNzQ0OTg3MTYxfQ.I00d0wKcdE5v5oonRH4yNPagWBNQ4D3NNMFBZluyMkc

### leader
# @refreshToken = 
# @accessToken = 

###
GET http://localhost:8888/api/v1/test_route

### 
POST http://localhost:8888/api/v1/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "user1"
}

###
GET http://localhost:8888/api/v1/logout
Cookie: refreshToken={{refreshToken}}

###
GET http://localhost:8888/api/v1/refresh
Cookie: refreshToken={{refreshToken}}

###
GET http://localhost:8888/api/v1/test_verifyJWT
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8888/api/v1/users
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8888/api/v1/user/6800eb6f039f52a3ac6b140b
Authorization: Bearer {{accessToken}}

###
POST http://localhost:8888/api/v1/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "0004",
    "name": "add",
    "email": "add@example.com",
    "password": "add",
    "role": "manager",
    "testType": "Physical Property Testing",
    "status": "active"
}

###
DELETE  http://localhost:8888/api/v1/user/680112c024a8cf6964f6ab32
Authorization: Bearer {{accessToken}}

###
PUT http://localhost:8888/api/v1/user/680112c024a8cf6964f6ab32
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "0004",
    "name": "add",
    "email": "add@example.com",
    "password": "add",
    "role": "manager",
    "testType": "Physical Property Testing",
    "status": "active"
}

