### manager
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjQ3NjhkZTNjMzU5NDMyODZiMTQwZCIsImVtYWlsIjoidXNlcjNAZXhhbXBsZS5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzQ3MjIwMTY1LCJleHAiOjE3NDcyMjM3NjV9.gaexfDUdz--3BeOpckwT2cb0ByWb79KXIpvBi2dzt40
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjQyMmUyOGM5N2FkOGQ3ZTZiMTQwZCIsImVtYWlsIjoidXNlcjNAZXhhbXBsZS5jb20iLCJyb2xlIjoibWVtYmVyIiwiaWF0IjoxNzQ3MjAyMTIzLCJleHAiOjE3NDcyODg1MjN9.O3R3IKC_GQdcQfVOOqFaBKLFY4ujafGh8ZT7U7UIXYQ

### leader
# @refreshToken = 
# @accessToken = 

###
GET http://localhost:8888/api/v1/test_route

### 
POST http://localhost:8888/api/v1/login
Content-Type: application/json

{
  "email": "user3@example.com",
  "password": "user3"
}

###
GET http://localhost:8888/api/v1/logout
Cookie: refreshToken={{refreshToken}}

###
GET http://localhost:8888/api/v1/refresh
Cookie: refreshToken={{refreshToken}}

###
GET http://localhost:8888/api/v1/test_verifyJWT
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8888/api/v1/user
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8888/api/v1/users
Authorization: Bearer {{accessToken}}

###
GET http://localhost:8888/api/v1/user/682422e28c97ad8d7e6b140d
Authorization: Bearer {{accessToken}}

###
POST http://localhost:8888/api/v1/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "0004",
    "name": "add",
    "email": "add@example.com",
    "password": "add",
    "role": "manager",
    "testType": "Physical Property Testing",
    "status": "active"
}

###
DELETE  http://localhost:8888/api/v1/user/680112c024a8cf6964f6ab32
Authorization: Bearer {{accessToken}}

###
PUT http://localhost:8888/api/v1/user/680112c024a8cf6964f6ab32
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "userId": "0004",
    "name": "add",
    "email": "add@example.com",
    "password": "add",
    "role": "manager",
    "testType": "Physical Property Testing",
    "status": "active"
}

