version: '3'
services:
  db:
    image: mongo-inited
    container_name: mongodb
    build:
      context: .
      dockerfile: dockerfile.init.db
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  mini-lab-api:
    image: mini-lab-api
    container_name: mini-lab-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - db
    volumes:
      - /var/log/mini-lab:/var/log/mini-lab

volumes:
  dbdata: